[mypy]
python_version = 3.14
packages = app, scripts
ignore_missing_imports = True
strict = False
warn_unused_configs = True

# Treat tests as less strict for now.
[mypy-tests.*]
ignore_errors = True
